"""
This script is used for course notes.

Author: Erick Marin
Date: 11/28/2020
"""

# Creating a file object and assigning a variable.
file = open("Course_2/Week_2/spider.txt")

# The operating system checks that we have permissions to access that file and
# then gives our code a file descriptor. This is a token generated by the OS
# that allows programs to do more operations with the file. This file
# descriptor is stored as an attribute of the files object. The file object
# gives us a bunch of methods that we can use to operate with the file.

print(file.readline())

# each time we call the readline method, the file object updates the current
# position in the file. So it keeps moving forward. We can also call the read
# method, which reads from the current position until the end of the file
# instead of just one line.
print(file.readline())

# The read method starts reading from wherever we currently are in the file.
# But instead of just one line, it reads all the way through to the files end.
print(file.read())

# Then we close the file.  Open-use-close pattern.
file.close()

# To help us remember to close the file after at the we're done using it,
# Python lets us create a block of code by using the keyword "with". When we
# use a "with" block, Python will automatically close the file. So we don't
# need to remember to do that ourselves.
with open("Course_2/Week_2/spider.txt") as file:
    print(file.readline())
